#language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t antonkovbasa/docker-example -f Dockerfile.dev .

script:
  - docker run -e CI=true antonkovbasa/docker-example npm run test